repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        args: ['--skip-string-normalization', '--line-length', '79']

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        exclude: '^(?!versions/)'
        files: ^(bot/|core/|src/)
        language: system
        types: [python]

      - id: flake8
        additional_dependencies: [Flake8-pyproject]
        name: flake8
        entry: flake8
        exclude: '^(?!versions/)'
        files: ^(bot/|core/|src/)
        language: python
        types: [python]
        args: ['--max-line-length=79']
