version: '3.8'

services:

  postgres:
    container_name: postgres
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.postgres_multiple
    volumes:
      - db_init_volume:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  admin_django:
    container_name: admin_django
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.admin_django
    restart: always
    volumes:
      - static_files_volume:/admin_django/static/
    depends_on:
      - postgres
    env_file:
      - ../.env

  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_files_volume:/var/html/static/
    depends_on:
      - admin_django

  tg_bot_second_wind:
    container_name: tg_bot_second_wind
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.bot
    depends_on:
      - nginx
    env_file:
      - ../.env

volumes:
  db_init_volume:
  db_volume:
  static_files_volume:
